use serde::{Deserialize, Serialize};
use std::path::PathBuf;

use crate::core::agent::{clean_markdown_with_report, extract_outline};
use crate::core::io::read_markdown_file_safe;
use crate::tui::app::flatten_headings;

pub const DEFAULT_LLMS_TXT_FILENAME: &str = "llms.txt";
pub const DEFAULT_LLMS_FULL_TXT_FILENAME: &str = "llms-full.txt";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LlmsTxtOutput {
    pub index_content: String,
    pub full_content: String,
    pub files_processed: usize,
    pub total_raw_tokens: usize,
    pub total_clean_tokens: usize,
    pub tokens_saved: usize,
}

/// Generates standardized llms.txt index and llms-full.txt AST-cleaned payload across markdown paths
pub fn generate_llmstxt(paths: &[PathBuf]) -> LlmsTxtOutput {
    let mut index_content = String::new();
    let mut full_content = String::new();
    let mut files_processed = 0;
    let mut total_raw_tokens = 0;
    let mut total_clean_tokens = 0;

    index_content.push_str("# Project Documentation Index\n\n> Generated by Pankh (🪶) AI Documentation Engine.\n\n## Files & Section Outlines\n\n");

    for (i, path) in paths.iter().enumerate() {
        if let Ok(content) = read_markdown_file_safe(path) {
            files_processed += 1;
            let report = clean_markdown_with_report(&content);
            total_raw_tokens += report.raw_tokens;
            total_clean_tokens += report.cleaned_tokens;

            let file_name = path.file_name().unwrap_or_default().to_string_lossy();
            let file_display = path.display().to_string();

            let outline = extract_outline(&content);
            let flat_headings = flatten_headings(&outline.headings);

            let main_title = flat_headings
                .first()
                .map(|h| h.title.as_str())
                .unwrap_or(file_name.as_ref());

            index_content.push_str(&format!(
                "- [{}]({}): {} (Tokens: {})\n",
                file_name, file_display, main_title, report.cleaned_tokens
            ));

            for heading in &flat_headings {
                let indent = "  ".repeat(heading.level as usize);
                index_content.push_str(&format!(
                    "{} - H{}: {}\n",
                    indent, heading.level, heading.title
                ));
            }

            if i > 0 && !full_content.is_empty() {
                full_content.push_str("\n\n---\n\n");
            }
            full_content.push_str(&format!("<!-- Source: {} -->\n\n", file_display));
            full_content.push_str(&report.cleaned_text);
        }
    }

    let tokens_saved = total_raw_tokens.saturating_sub(total_clean_tokens);

    LlmsTxtOutput {
        index_content,
        full_content,
        files_processed,
        total_raw_tokens,
        total_clean_tokens,
        tokens_saved,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs::File;
    use std::io::Write;

    #[test]
    fn test_generate_llmstxt_index_and_full() {
        let temp_dir = std::env::temp_dir();
        let f1_path = temp_dir.join("llms_test_1.md");
        let mut f1 = File::create(&f1_path).unwrap();
        writeln!(f1, "# Main Title\n\n[![badge](https://img.shields.io/badge)](https://a.com)\n\n## Sub Title\n\nContent body.").unwrap();

        let output = generate_llmstxt(std::slice::from_ref(&f1_path));
        assert_eq!(output.files_processed, 1);
        assert!(output.index_content.contains("Main Title"));
        assert!(output.index_content.contains("Sub Title"));
        assert!(output.full_content.contains("Content body."));
        assert!(!output.full_content.contains("img.shields.io"));

        let _ = std::fs::remove_file(f1_path);
    }
}
